token_map = {
"redacted":["Insurance","A","1"],
"redacted":["Insurance","A","2"],
"redacted":["Insurance","A","3"],
"redacted":["Insurance","A","4"],
"redacted":["Insurance","A","5"],
"redacted":["Insurance","A","6"],
"redacted":["Insurance","A","7"],
"redacted":["Insurance","A","8"],
"redacted":["Insurance","A","1"],
"redacted":["Insurance","A","2"],
"redacted":["Insurance","A","2"],
"redacted":["Insurance","A","3"],
"redacted":["Insurance","A","4"],
"redacted":["Insurance","A","5"],
"redacted":["Insurance","A","6"],
"redacted":["Insurance","A","7"],
"redacted":["Insurance","A","7"],
"redacted":["Insurance","A","8"],
"redacted":["Insurance","A","9"],
"redacted":["Technology","B","1"],
"redacted":["Insurance","B","1"],
"redacted":["Insurance","B","2"],
"redacted":["Insurance","B","3"],
"redacted":["Insurance","B","4"],
"redacted":["Insurance","B","1"],
"redacted":["Insurance","B","2"],
"redacted":["Insurance","B","3"],
"redacted":["Insurance","B","4"],
"redacted":["Retail","A","1"],
"redacted":["Retail","A","2"],
"redacted":["Retail","A","1"],
"redacted":["Retail","A","2"],
"redacted":["Banking","A","1"],
"redacted":["Banking","A","2"],
"redacted":["Banking","A","2"],
"redacted":["Banking","A","3"],
"redacted":["Banking","A","4"],
"redacted":["Banking","A","5"],
"redacted":["Banking","A","3"],
"redacted":["Banking","A","4"],
"redacted":["Banking","A","5"],
"redacted":["Insurance","C","1"],
"redacted":["Insurance","C","2"],
"redacted":["Insurance","C","3"],
"redacted":["Insurance","C","4"],
"redacted":["Insurance","C","5"],
"redacted":["Insurance","C","6"],
"redacted":["Solicitors","A","1"],
"redacted":["Solicitors","A","2"],
"redacted":["Solicitors","A","1"],
"redacted":["Solicitors","A","2"],
"redacted":["Solicitors","A","3"],
"redacted":["General","G","1"],
"redacted":["General","G","1"],
"redacted":["General","G","1"],
"redacted":["Retail","B","1"],
"redacted":["Web service","A","1"],
"redacted":["Web service","A","2"],
"redacted":["Web service","A","3"],
"redacted":["Web service","A","4"],
"redacted":["Web service","A","2"],
"redacted":["Web service","A","3"],
"redacted":["Web service","A","4"],
"redacted":["Technology","A","1"],
"redacted":["Technology","A","2"],
"redacted":["Technology","A","3"],
"redacted":["Technology","A","4"],
"redacted":["Technology","A","5"],
"redacted":["Technology","A","6"],
"redacted":["Technology","A","7"],
"redacted":["Technology","A","8"],
"redacted":["Technology","A","1"],
"redacted":["Technology","A","2"],
"redacted":["Technology","A","3"],
"redacted":["Technology","A","4"],
"redacted":["Technology","A","5"],
"redacted":["Technology","A","6"],
"redacted":["Technology","A","8"],
"redacted":["Finance","A","1"],
"redacted":["Finance","A","2"],
"redacted":["Finance","A","2"],
"redacted":["Media","A","1"],
"redacted":["Retail","C","1"],
"redacted":["Retail","C","2"],
"redacted":["Retail","C","2"],
"redacted":["Retail","C","3"],
"redacted":["Retail","C","3"]

}